### PR TITLE
Added support for classes deeper than immediate subclasses of FTASyncParent

### PR DESCRIPTION
**Pull request by AndrewSmall**

### CODE REVIEW

**Comment by itsniper** [comment]
Awesome thanks! I'll try and take a look this weekend.

**Comment by AndrewSmall** [comment]
Thanks to you!

The next thing would be to add support for Parse PFRelations. I saw a TODO
in there about upgrading to a new Parse SDK for that.

Andrew

**Comment by itsniper** [comment]
Yeah, the included SDK has it in there. But it was added after I was already setup with doing relationships the "old" way.

**Comment by itsniper** [comment]
Merged in the pull request on Saturday, but now sync is not working properly. So I'm working on debugging that. Hopefully can get it resolved soon.

**Comment by itsniper** [comment]
One issue ended up being an object ID issue in Magical Record 2. Adding a todo item to a person created during this run session was causing a "ghost" person managedObject. Pulling in a more recent version of MR (magicalpanda/MagicalRecord@abb7314b26877982f44933998782056f43d61b8c) seems to have fixed it. I believe it was the permanent id fixes put in MR on 9/28.

**Comment by AndrewSmall** [comment]
Thanks Justin. Do you have any idea how big is a migration to the new
PFRelations from the old style? I am not familiar with the old style.

Andrew

**Comment by itsniper** [comment]
It may be a fair bit of work to do it properly. The biggest issue is going to be the conflict resolution code. As I was reminded today, that code is fairly complex and fragile. I opened Issue #3 for this, so we can move the convo over there.

**Comment by itsniper** [comment]
Fixed the final issue. Adding support for custom data class names had broken the relationship conflict resolution. Fixed with commit 2423154084a496c08f8912cb8e9f7381e9fbe012 .

**Pull request closed without merging**
